/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.JLabel;

/**
 *
 * @author italo
 */
public class SOMInfoPNL extends javax.swing.JPanel {

    /**
     * Creates new form SOMConfigInfoPNL
     */
    public SOMInfoPNL() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        quantITsLBV = new javax.swing.JLabel();
        vizinhancaLBV = new javax.swing.JLabel();
        gradeDimLBV = new javax.swing.JLabel();
        gradeNDistLBV = new javax.swing.JLabel();
        taIniLBV = new javax.swing.JLabel();
        taFinalLBV = new javax.swing.JLabel();
        rvIniLBV = new javax.swing.JLabel();
        rvFinalLBV = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        iteracaoLBV = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        taCorrenteLBV = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        rvCorrenteLBV = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(230, 360));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("Nº de iterações:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Vizinhança:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("Grade. Dimensão:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("Grade Neu. Dist.:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setText("Taxa de aprendizado:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setText("Inicial:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setText("Final:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel8.setText("Raio de vizinhança:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel9.setText("Inicial:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel10.setText("Final:");

        quantITsLBV.setForeground(new java.awt.Color(51, 102, 255));
        quantITsLBV.setText("padrão");

        vizinhancaLBV.setForeground(new java.awt.Color(51, 102, 255));
        vizinhancaLBV.setText("padrão");

        gradeDimLBV.setForeground(new java.awt.Color(51, 102, 255));
        gradeDimLBV.setText("padrão");

        gradeNDistLBV.setForeground(new java.awt.Color(51, 102, 255));
        gradeNDistLBV.setText("padrão");

        taIniLBV.setForeground(new java.awt.Color(51, 102, 255));
        taIniLBV.setText("padrão");

        taFinalLBV.setForeground(new java.awt.Color(51, 102, 255));
        taFinalLBV.setText("padrão");

        rvIniLBV.setForeground(new java.awt.Color(51, 102, 255));
        rvIniLBV.setText("padrão");

        rvFinalLBV.setForeground(new java.awt.Color(51, 102, 255));
        rvFinalLBV.setText("padrão");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel11.setText("Iteração:");

        iteracaoLBV.setForeground(new java.awt.Color(51, 102, 255));
        iteracaoLBV.setText("padrão");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel12.setText("Corrente:");

        taCorrenteLBV.setForeground(new java.awt.Color(0, 102, 255));
        taCorrenteLBV.setText("padrão");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel14.setText("Corrente:");

        rvCorrenteLBV.setForeground(new java.awt.Color(0, 102, 255));
        rvCorrenteLBV.setText("padrão");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel11)
                        .addGap(7, 7, 7)
                        .addComponent(iteracaoLBV))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1)
                        .addGap(7, 7, 7)
                        .addComponent(quantITsLBV))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel2)
                        .addGap(7, 7, 7)
                        .addComponent(vizinhancaLBV))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel6)
                        .addGap(7, 7, 7)
                        .addComponent(taIniLBV))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel7)
                        .addGap(7, 7, 7)
                        .addComponent(taFinalLBV))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel12)
                        .addGap(7, 7, 7)
                        .addComponent(taCorrenteLBV))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel9)
                        .addGap(7, 7, 7)
                        .addComponent(rvIniLBV))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel10)
                        .addGap(7, 7, 7)
                        .addComponent(rvFinalLBV))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel14)
                        .addGap(7, 7, 7)
                        .addComponent(rvCorrenteLBV))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(gradeDimLBV))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(7, 7, 7)
                                .addComponent(gradeNDistLBV)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(iteracaoLBV))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(quantITsLBV))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(vizinhancaLBV))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(gradeDimLBV))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(gradeNDistLBV))
                .addGap(7, 7, 7)
                .addComponent(jLabel5)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(taIniLBV))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(taFinalLBV))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(taCorrenteLBV))
                .addGap(13, 13, 13)
                .addComponent(jLabel8)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(rvIniLBV))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(rvFinalLBV))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(rvCorrenteLBV)))
        );
    }// </editor-fold>//GEN-END:initComponents

    public JLabel getIteracaoLBV() {
        return iteracaoLBV;
    }

    public JLabel getGradeDimLBV() {
        return gradeDimLBV;
    }

    public JLabel getGradeNDistLBV() {
        return gradeNDistLBV;
    }

    public JLabel getQuantITsLBV() {
        return quantITsLBV;
    }

    public JLabel getRvFinalLBV() {
        return rvFinalLBV;
    }

    public JLabel getRvIniLBV() {
        return rvIniLBV;
    }

    public JLabel getTaFinalLBV() {
        return taFinalLBV;
    }

    public JLabel getTaIniLBV() {
        return taIniLBV;
    }

    public JLabel getVizinhancaLBV() {
        return vizinhancaLBV;
    }

    public JLabel getRvCorrenteLBV() {
        return rvCorrenteLBV;
    }

    public JLabel getTaCorrenteLBV() {
        return taCorrenteLBV;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel gradeDimLBV;
    private javax.swing.JLabel gradeNDistLBV;
    private javax.swing.JLabel iteracaoLBV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel quantITsLBV;
    private javax.swing.JLabel rvCorrenteLBV;
    private javax.swing.JLabel rvFinalLBV;
    private javax.swing.JLabel rvIniLBV;
    private javax.swing.JLabel taCorrenteLBV;
    private javax.swing.JLabel taFinalLBV;
    private javax.swing.JLabel taIniLBV;
    private javax.swing.JLabel vizinhancaLBV;
    // End of variables declaration//GEN-END:variables
}
